// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBChIE_Hp1V-Z6PdplPbag4y8NbMlMuK4o',
    appId: '1:403216946829:web:56135487822f772f8c74c4',
    messagingSenderId: '403216946829',
    projectId: 'auth-97ae9',
    authDomain: 'auth-97ae9.firebaseapp.com',
    storageBucket: 'auth-97ae9.firebasestorage.app',
    measurementId: 'G-K9ZX76YH7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjbka7vqLFf9fu8wQfM8CpwxsQwSh1zSA',
    appId: '1:403216946829:android:9d0a72ea25e6a8e18c74c4',
    messagingSenderId: '403216946829',
    projectId: 'auth-97ae9',
    storageBucket: 'auth-97ae9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW_YLZOBww_cnKaJTjoGFs_BcHOkNWpwM',
    appId: '1:403216946829:ios:5fffa460425f5c978c74c4',
    messagingSenderId: '403216946829',
    projectId: 'auth-97ae9',
    storageBucket: 'auth-97ae9.firebasestorage.app',
    iosClientId: '403216946829-chbetv3mk8vgjtmm98s04vrd6rbsuvs0.apps.googleusercontent.com',
    iosBundleId: 'com.example.bsuniverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW_YLZOBww_cnKaJTjoGFs_BcHOkNWpwM',
    appId: '1:403216946829:ios:5fffa460425f5c978c74c4',
    messagingSenderId: '403216946829',
    projectId: 'auth-97ae9',
    storageBucket: 'auth-97ae9.firebasestorage.app',
    iosClientId: '403216946829-chbetv3mk8vgjtmm98s04vrd6rbsuvs0.apps.googleusercontent.com',
    iosBundleId: 'com.example.bsuniverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBChIE_Hp1V-Z6PdplPbag4y8NbMlMuK4o',
    appId: '1:403216946829:web:b073e25077b134248c74c4',
    messagingSenderId: '403216946829',
    projectId: 'auth-97ae9',
    authDomain: 'auth-97ae9.firebaseapp.com',
    storageBucket: 'auth-97ae9.firebasestorage.app',
    measurementId: 'G-CGXFEBLRJG',
  );

}