import 'package:flutter/material.dart';
// PURELY GENERATED BY CHATGPT TY TO IT
class BouncingArrow extends StatefulWidget {
  const BouncingArrow({super.key}); 

  @override
  State<BouncingArrow> createState() => _BouncingArrowState();
}

class _BouncingArrowState extends State<BouncingArrow> with SingleTickerProviderStateMixin {
  late final AnimationController _controller;

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 800),
    )..repeat(reverse: true); 
  }

  @override
  void dispose() {
    _controller.dispose(); // cleanup to prevent memory leak
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: _controller,
      builder: (context, child) {
        // Bounce animation from 0 to 10 pixels down
        final bounce = Tween(begin: 0.0, end: 10.0)
            .chain(CurveTween(curve: Curves.easeInOut))
            .evaluate(_controller);

        return Transform.translate(
          offset: Offset(0, bounce),
          child: const Icon(
            Icons.arrow_drop_down_rounded,
            color: Colors.white,
            size: 60.0,
          ),
        );
      },
    );
  }
}
